changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - invalid-author
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Fixes 🔧
      labels:
        - fix
        - bug
    - title: Performance 🏎
      labels:
        - performance
    - title: '🧰 Maintenance'
      labels:
        - build
        - ci
    #        - "infrastructure"
    #        - "automation"
    #        - "documentation"
    - title: Other Changes 🧹
      labels:
        - '*'
