#file: noinspection SpellCheckingInspection
name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set JDK/Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          
      - name: Get version number from tag
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false --batch-mode --no-transfer-progress

      - name: Build with Maven
        run: mvn clean package -V -B -ntp

      - name: Codecov Coverage Reporter
        uses: codecov/codecov-action@v4

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/site/jacoco/jacoco.xml

      - name: Publish package
        run: mvn deploy -DskipTests -V -B -ntp -Dlicense.skip=true
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            target/*.jar
